insert into breed (name, active, created_at, updated_at)
values ('믹스견', true, current_timestamp, current_timestamp),
       ('견종 미상', true, current_timestamp, current_timestamp),
       ('말티즈', true, current_timestamp, current_timestamp),
       ('푸들', true, current_timestamp, current_timestamp),
       ('포메라니안', true, current_timestamp, current_timestamp),
       ('비숑 프리제', true, current_timestamp, current_timestamp),
       ('시추', true, current_timestamp, current_timestamp),
       ('요크셔테리어', true, current_timestamp, current_timestamp),
       ('치와와', true, current_timestamp, current_timestamp),
       ('닥스훈트', true, current_timestamp, current_timestamp),
       ('미니어처 슈나우저', true, current_timestamp, current_timestamp),
       ('프렌치 불도그', true, current_timestamp, current_timestamp),
       ('퍼그', true, current_timestamp, current_timestamp),
       ('골든 리트리버', true, current_timestamp, current_timestamp),
       ('래브라도 리트리버', true, current_timestamp, current_timestamp),
       ('웰시 코기', true, current_timestamp, current_timestamp),
       ('비글', true, current_timestamp, current_timestamp),
       ('보더 콜리', true, current_timestamp, current_timestamp),
       ('사모예드', true, current_timestamp, current_timestamp),
       ('진돗개', true, current_timestamp, current_timestamp),
       ('시베리안 허스키', true, current_timestamp, current_timestamp),
       ('독일 셰퍼드', true, current_timestamp, current_timestamp),
       ('코커 스패니얼', true, current_timestamp, current_timestamp),
       ('셔틀랜드 쉽독', true, current_timestamp, current_timestamp);
